DROP TABLE IF EXISTS VENDEDORES;

CREATE TABLE VENDEDORES(
    id INT AUTO_INCREMENT PRIMARY KEY,
    data_inclusao DATE NOT NULL,
    nome VARCHAR(250) NOT NULL,
    telefone VARCHAR(250) NOT NULL,
    idade INT NOT NULL,
    cidade VARCHAR(250) NOT NULL,
    estado VARCHAR(250) NOT NULL,
    regiao VARCHAR(250) NOT NULL
);